export default [
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'The Sniper',
    releaseDate: '13/03/1905',
    duration: '2h 51m',
    maturity: 'R',
    genres: ['Horror', 'Comedy', 'Action'],
    director: 'Salomon Eslinger',
    mainActors: ['Dilly Mazillius', 'Adrian McElvogue'],
    plot: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    metascore: 96,
    rating: 9.3,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Time Limit',
    releaseDate: '24/06/1968',
    duration: '3h 23m',
    maturity: 'NC-17',
    genres: ['Sci-Fi', 'Drama'],
    director: 'Lanette Besson',
    mainActors: ['Johnath Lapsley', 'Robenia Stringman', 'Carrol MacGruer'],
    plot: 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    metascore: 53,
    rating: 7.6,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Home from the Hill',
    releaseDate: '06/07/1953',
    duration: '2h 23m',
    maturity: 'PG-13',
    genres: ['Horror', 'Adventure', 'Fantasy'],
    director: 'Emerson Guare',
    mainActors: ['Feliks Allsworth', 'Rosemaria Pasley', 'Stacie Wynter'],
    plot: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    metascore: 91,
    rating: 7.1,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'One Fine Spring Day (Bomnaleun ganda)',
    releaseDate: '27/06/1988',
    duration: '2h 17m',
    maturity: 'NC-17',
    genres: ['Drama', 'Comedy', 'Sci-Fi'],
    director: 'Kennett Rolland',
    mainActors: ['Adele Wallwood'],
    plot: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    metascore: 68,
    rating: 6.7,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'War of the Worlds',
    releaseDate: '23/10/1914',
    duration: '2h 41m',
    maturity: 'NC-17',
    genres: ['Horror'],
    director: 'Petronilla Smaling',
    mainActors: ['Merralee Vickerstaff', 'Padgett Kupec', 'Evelina Schott'],
    plot: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    metascore: 46,
    rating: 5.2,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Far Side of the Moon (Loin des phares)',
    releaseDate: '29/01/1993',
    duration: '2h 23m',
    maturity: 'PG-13',
    genres: ['Drama', 'Drama', 'Sci-Fi'],
    director: 'Alta Buswell',
    mainActors: ['Sande Cumbers', 'Lori Kimbell'],
    plot: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis bibendum.',
    metascore: 52,
    rating: 5.8,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Madagascar: A Journey Diary',
    releaseDate: '10/8/1973',
    duration: '4h 30m',
    maturity: 'PG-13',
    genres: ['Drama', 'Horror', 'Action'],
    director: 'Benn Smith',
    mainActors: ['Jule Mound', 'Fina Malloy', 'Hatti Kneath'],
    plot: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
    metascore: 64,
    rating: 5.2,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Kings of the Ring: Four Legends of Heavyweight Boxing',
    releaseDate: '14/12/1919',
    duration: '4h 01m',
    maturity: 'PG-13',
    genres: ['Comedy', 'Drama', 'Horror'],
    director: 'Feliza Moxom',
    mainActors: ['Dill Embleton', 'Rance Slane', 'Meghan Jotcham'],
    plot: 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
    metascore: 83,
    rating: 5.6,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Rush (Sokout)',
    releaseDate: '12/6/1994',
    duration: '1h 23m',
    maturity: 'PG',
    genres: ['Comedy', 'Comedy', 'Horror'],
    director: 'Melvyn Pearse',
    mainActors: ['Ermanno Lobley', 'Pavia Burchill'],
    plot: 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',
    metascore: 42,
    rating: 5.9,
  },
  {
    poster: 'https://dummyimage.com/200x250/f08011/080e6b.png&text=Peli+Poster',
    title: 'Couch Trip, The',
    releaseDate: '18/04/2005',
    duration: '3h 26m',
    maturity: 'PG-13',
    genres: ['Drama', 'Comedy', 'Sci-Fi'],
    director: 'Danita Drysdall',
    mainActors: ['Inessa Thickepenny', 'Brook Mantle'],
    plot: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    metascore: 63,
    rating: 6.2,
  },
];
